//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_JoystickClick;
        
        private static SteamVR_Action_Boolean p_default_TriggerOn;
        
        private static SteamVR_Action_Boolean p_default_GripOn;
        
        private static SteamVR_Action_Boolean p_default_A;
        
        private static SteamVR_Action_Boolean p_default_B;
        
        private static SteamVR_Action_Boolean p_default_X;
        
        private static SteamVR_Action_Boolean p_default_Y;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Vector2 p_default_Move;
        
        public static SteamVR_Action_Boolean default_JoystickClick
        {
            get
            {
                return SteamVR_Actions.p_default_JoystickClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_TriggerOn
        {
            get
            {
                return SteamVR_Actions.p_default_TriggerOn.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GripOn
        {
            get
            {
                return SteamVR_Actions.p_default_GripOn.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_A
        {
            get
            {
                return SteamVR_Actions.p_default_A.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_B
        {
            get
            {
                return SteamVR_Actions.p_default_B.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_X
        {
            get
            {
                return SteamVR_Actions.p_default_X.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Y
        {
            get
            {
                return SteamVR_Actions.p_default_Y.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_Move
        {
            get
            {
                return SteamVR_Actions.p_default_Move.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_JoystickClick,
                    SteamVR_Actions.default_TriggerOn,
                    SteamVR_Actions.default_GripOn,
                    SteamVR_Actions.default_A,
                    SteamVR_Actions.default_B,
                    SteamVR_Actions.default_X,
                    SteamVR_Actions.default_Y,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_Move};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_JoystickClick,
                    SteamVR_Actions.default_TriggerOn,
                    SteamVR_Actions.default_GripOn,
                    SteamVR_Actions.default_A,
                    SteamVR_Actions.default_B,
                    SteamVR_Actions.default_X,
                    SteamVR_Actions.default_Y,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_Move};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_JoystickClick,
                    SteamVR_Actions.default_TriggerOn,
                    SteamVR_Actions.default_GripOn,
                    SteamVR_Actions.default_A,
                    SteamVR_Actions.default_B,
                    SteamVR_Actions.default_X,
                    SteamVR_Actions.default_Y};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_Move};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_JoystickClick,
                    SteamVR_Actions.default_TriggerOn,
                    SteamVR_Actions.default_GripOn,
                    SteamVR_Actions.default_A,
                    SteamVR_Actions.default_B,
                    SteamVR_Actions.default_X,
                    SteamVR_Actions.default_Y,
                    SteamVR_Actions.default_Move};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_JoystickClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/JoystickClick")));
            SteamVR_Actions.p_default_TriggerOn = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TriggerOn")));
            SteamVR_Actions.p_default_GripOn = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GripOn")));
            SteamVR_Actions.p_default_A = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/A")));
            SteamVR_Actions.p_default_B = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/B")));
            SteamVR_Actions.p_default_X = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/X")));
            SteamVR_Actions.p_default_Y = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Y")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/Move")));
        }
    }
}
