//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean JoystickClick
        {
            get
            {
                return SteamVR_Actions.default_JoystickClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerOn
        {
            get
            {
                return SteamVR_Actions.default_TriggerOn;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripOn
        {
            get
            {
                return SteamVR_Actions.default_GripOn;
            }
        }
        
        public virtual SteamVR_Action_Boolean A
        {
            get
            {
                return SteamVR_Actions.default_A;
            }
        }
        
        public virtual SteamVR_Action_Boolean B
        {
            get
            {
                return SteamVR_Actions.default_B;
            }
        }
        
        public virtual SteamVR_Action_Boolean X
        {
            get
            {
                return SteamVR_Actions.default_X;
            }
        }
        
        public virtual SteamVR_Action_Boolean Y
        {
            get
            {
                return SteamVR_Actions.default_Y;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.default_Move;
            }
        }
    }
}
